unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

set -g prefix C-s

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind P paste-buffer
bind-key -T copy-mode-vi 'v'   send-keys -X rectangle-off \; send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-on  \; send -X begin-selection
bind-key -T copy-mode-vi 'y'   send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape {
    if-shell -F "#{selection_present}" {
        # true
        send-keys -X clear-selection
    } {
        # false
        send-keys -X cancel
    }
}

unbind-key -T copy-mode-vi MouseDragEnd1Pane
unbind-key -T copy-mode MouseDragEnd1Pane

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
