#+TITLE: B2F's GNU Emacs Config
#+AUTHOR: Andrey Akimov (Brown2Fox)
#+DESCRIPTION: B2F's personal Emacs config.
#+STARTUP: showeverything
#+OPTIONS: toc:2
 
* TABLE OF CONTENTS :toc:
- [[#introduction][Introduction]]
  - [[#what-is-kickstartemacs][What is Kickstart.emacs?]]
  - [[#ctrl--meta][Ctrl & Meta]]
  - [[#where-to-start][Where to start?]]
  - [[#getting-help][Getting Help]]
- [[#core-setup--performance][Core Setup & Performance]]
  - [[#startup-performance][Startup Performance]]
  - [[#auto-tangle-configuration-file][Auto-tangle Configuration file]]
  - [[#show-startup-time][Show startup time]]
  - [[#package-manager][Package manager]]
  - [[#good-defaults][Good Defaults]]
- [[#custom-recipes][Custom Recipes]]
- [[#additional-sources][Additional Sources]]
  - [[#adding-the-lisp-directory-to-load-path][Adding the lisp directory to load-path]]
  - [[#sourcing-the-files][Sourcing the files]]
  - [[#using-the-file][Using the file]]
- [[#evil-mode][Evil Mode]]
- [[#general-keybindings][General Keybindings]]
- [[#appearance][Appearance]]
  - [[#beacon-mode][Beacon Mode]]
  - [[#nerd-icons][Nerd Icons]]
  - [[#modeline][ModeLine]]
  - [[#rainbow-mode][Rainbow Mode]]
  - [[#theme][Theme]]
  - [[#transparency][Transparency]]
- [[#development][Development]]
  - [[#projectile][Projectile]]
  - [[#eglot][Eglot]]
  - [[#masonel][Mason.el]]
  - [[#sideline-flymake][Sideline-flymake]]
  - [[#yasnippet][Yasnippet]]
  - [[#snippy][Snippy]]
  - [[#tree-sitter][Tree-Sitter]]
- [[#cuamode][CuaMode]]
- [[#buffer-move][Buffer Move]]
- [[#completion][Completion]]
  - [[#company-mode][Company Mode]]
  - [[#save-history][Save History]]
  - [[#ivy--counsel][Ivy + Counsel]]
- [[#vertico-disabled][Vertico (Disabled)]]
- [[#dashboard][Dashboard]]
- [[#dired][Dired]]
- [[#language-support][Language Support]]
  - [[#odin][Odin]]
- [[#multiple-cursors][Multiple Cursors]]
- [[#org-mode][Org Mode]]
  - [[#enabling-table-of-contents][Enabling Table of Contents]]
  - [[#enabling-org-bullets][Enabling Org Bullets]]
  - [[#disable-electric-indent][Disable Electric Indent]]
  - [[#shift-select][Shift Select]]
  - [[#org-level-headers][Org Level Headers]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
- [[#terminal][Terminal]]
  - [[#eat][Eat]]
  - [[#exec-path-from-shell][Exec-path-from-shell]]
- [[#scroll-behavior][Scroll Behavior]]
- [[#which-key][Which Key]]
- [[#uncategorized][Uncategorized]]

* Introduction
#+begin_src emacs-lisp :tangle no
    ;;==================================================================;;
    ;;================== READ THIS BEFORE CONTINUING ===================;;
    ;;==================================================================;;
    ;;======                                    .-----.          =======;;
    ;;======         .----------------------.   | === |          =======;;
    ;;======         |.-""""""""""""""""""-.|   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         ||  'KICKSTART.EMACS' ||   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         || M-X:               ||   |-----|          =======;;
    ;;======         || help-with-tutorial ||   |:::::|          =======;;
    ;;======         |'-..................-'|   |____o|          =======;;
    ;;======         `"")----------------(""`   ____________     =======;;
    ;;======        /::::::::::|  |:::::p::::\  \ Only CTRL \    =======;;
    ;;======       /:::=======f|  |========:::\  \ required  \   =======;;
    ;;======      'CTRL""""""""'  'bn""""""""""'  '""""""""""'   =======;;
    ;;======                                                     =======;;
    ;;==================================================================;;
    ;;==================================================================;;
#+end_src

** What is Kickstart.emacs?
Kickstart.emacs is *not* a distribution.
It's a template for your own configuration.
Inspired by kickstart.nvim.

It is *recommended* to configure it from the *init.org* file.

Kickstart.emacs is a starting point for your own configuration.
The goal is that you read every line, top-to-bottom, understand
what your configuration is doing, and modify it to suit your needs.

After you've done that, you can start making your own configuration out of this
or taking the things you like and making something new from scratch.
The choice is yours. You can do basically anything with Emacs.
So don't hesitate to try things out.

You can delete this when you're done. It's your config now. :)
I hope you have fun with your Emacs journey.
MiniApollo

** Ctrl & Meta
This is from the Emacs tutorial, but I put this here for safety.

Emacs commands generally involve the CONTROL key (often labeled CTRL)
or the META key (usually labeled ALT). Rather than writing that
in full each time, we'll use the following abbreviations:

C-<chr>  means hold the CONTROL key while typing the character <chr>.
Thus, C-f would be: hold the CONTROL key and type f.
M-<chr>  means hold the META or ALT key down while typing <chr>.
If there is no META or ALT key, instead press and release the
ESC key and then type <chr>.  We write <ESC> for the ESC key.

** Where to start?
First I recommend starting with the Emacs tutorial with the following keybinding: C-h t
Or running the command with M-x: help-with-tutorial
Even if you plan on using Vim keybindings later on, it's a good idea to learn the standard Emacs keybindings.
If you already know the standard Emacs keybindings, you can skip this step.

After you completed that, you should start learning Emacs lisp.
It is not necessary to know elisp, but I recommend it. It will open up a whole new world, trust me.
I used Emacs and Neovim without knowing much about the core language and just copy pasting packages or plugins.
But after learning the fundamentals you can customize basically anything and I really mean ANYTHING.

This will look daunting at first, but don't be scared. This is why I am here.
Elisp is not harder than lua or any other language.

If you don't know anything about elisp, I recommend taking some time to read through
a guide. One possible example which will only take 10-15 minutes:
https://learnxinyminutes.com/elisp/

Or if you want to know everything about elisp:
https://www.gnu.org/software/emacs/manual/html_node/eintr/

** Getting Help
If you get stuck or confused about something, you're in luck:
Because Emacs has a really good help functionality.
Everything under C-h is used for help keybindings.

Using the following keybind: C-h C-h
Or running the following command M-x: help-for-help
Will open up the Emacs help for help menu (I know it's a really creative name :D).
This is the central place where you can see all possible commands you can use when you are stuck.

The most used commands for me are:
- C-h v Describe variable
- C-h f Describe function
- C-h k Describe key

Other also really useful ones:
- C-h i Show all installed manuals
- C-h r Emacs manual
- C-h a Search for commands (see also M-x: Apropos)
- C-h m Show help for current major and minor modes

These commands should be the first thing you use when you're stuck or confused with something.

*** Searching the manual
The manual has a specific mode called info-mode.
Which has useful features you can use.
For more about info-mode: C-h f: info-mode

Basic navigation:
- d key: Go back to the top-level Info Directory.
- u key: Go up to the parent node in the document's hierarchy.
- n key: for next node in the current manual.
- p key: for previous node in the current manual.

*Note:* A Node is essentially a specific section or topic, much like a chapter or subsection in a book.

When you are browsing through the Emacs manual you can easily search with:
- i key: for specific subjects in the current manual.
- g key: for nodes (sections).
- m key: for menu items within the current Info buffer.
- s key: for regular expression patterns (like words) within the current Info buffer.

For evil users after setting up evil collection for info mode:
- g-j: for next node in the current manual.
- g-k: for previous node in the current manual.
- g-G: for nodes (sections).
- g-m: for menu items within the current Info buffer.
- The other keybinds are the same
To see all the evil [[https://github.com/emacs-evil/evil-collection/blob/master/modes/info/evil-collection-info.el][keybindings]] for info mode.

Using goto-node:
- Specify a Manual: If you want to search within a particular manual, place its name in parentheses like (emacs).
- After that tell where you want to go in that manual. For example (emacs)Top, (emacs)specific section.
- If you don't type a manual name, goto-node will search the currently opened manual.

* Core Setup & Performance
These are essential settings and small tweaks that must load before any packages.
They impact the entire configuration, skipping these could result in significantly slower configuration and potential breakage of your setup.

** Startup Performance
Core performance tweaks moved to early-init.el
See: [[https://github.com/doomemacs/doomemacs/issues/310][Why is doom emacs so fast?]]

*** Lexical-bindings
Gives better performance, lexical closures, and code safety, allowing local variables to remain truly local.
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

*** Early-Init.el
This file is loaded before anything else.
Most of the performance tweaks are there.
We can configure things before the GUI or other packages are loaded.

** Auto-tangle Configuration file
Auto-Tangle Org configuration file for better startup times, it refreshes the package-quickstart file.
We'll cover package quickstart in the package manager section later.

If you like to auto tangle an Org file, don't forget to add the following line to the top of your Org document:
(#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the init.el file won't update on change!
To fix this, you need to find this file (C-x C-f), fix the error and press C-c C-v t to tangle it manually.

This snippet adds a hook to org-mode buffers so that start/org-babel-tangle-config gets executed each time such a buffer gets saved.
This function checks to see if the file being saved is the init.org file you're looking at right now, and if so,
automatically exports the configuration here to the associated output files.
#+begin_src emacs-lisp
(defun start/org-babel-tangle-config ()
  "Automatically tangle our init.org config file and refresh package-quickstart when we save it. Credit to Emacs From Scratch for this one!"
  (interactive)
  (when (string-equal (file-name-directory (buffer-file-name))
                      (expand-file-name user-emacs-directory))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle)
      (package-quickstart-refresh))
  )
)

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-config)))
#+end_src

** Show startup time
#+begin_src emacs-lisp
(defun start/display-startup-time ()
  (interactive)
  (message "Emacs loaded in %s with %d garbage collections."
            (format "%.2f seconds"
                    (float-time
                    (time-subtract after-init-time before-init-time)))
            gcs-done))

(add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

** Package manager
We use the default built in package manager package.el.

Alternative package managers (straight.el, elpaca, etc.) are useful if you want:
- Faster package installation.
- Lock file support for recovery if something goes wrong.
- Packages that are cloned as Git (or other) repositories, not as opaque tarballs.
- Better UI
- Async support

If you are interested in using other package managers, check out their git repositories.
To learn more about why something like [[https://github.com/doomemacs/doomemacs/blob/master/docs/faq.org#why-does-doom-use-straightel-and-not-packageel][doomemacs uses]] straight.el not package.el.

In my experience Package.el is not slow and gets the job done.

To update/upgrade packages, use the package-upgrade-all command.
Package.el has a UI. Check it out with M-x list-packages.

*** Use-package
A macro that allows you to isolate package configuration in your .emacs file in a way that is both performance-oriented and, well, tidy.
We use it because it makes package configuration really easy.

With Emacs 29 use-package is now built-in.

This code eliminates the need to type :ensure t for each package download.
Instead, you'll only need to use :ensure nil when you want to explicitly prevent a package from being downloaded.
#+begin_src emacs-lisp
(require 'use-package-ensure) ;; Load use-package-always-ensure
(setq use-package-always-ensure t) ;; Always ensures that a package is installed
#+end_src

*** Setting package repositories
Like Linux distributions, Emacs uses repositories to manage its packages.
#+begin_src emacs-lisp
(setq package-archives '(("melpa" . "https://melpa.org/packages/") ;; Sets default package repositories
                          ("elpa" . "https://elpa.gnu.org/packages/")
                          ("nongnu" . "https://elpa.nongnu.org/nongnu/"))) ;; For Eat Terminal
#+end_src

*** Package quickstart
Improves startup times by allowing Emacs to precompute and generate a single, large autoload file.
Instead of re-computing them on every startup.

The larger your configuration, the more it will be felt at startup.

However, if you enable this, you'll need to manually run the package-quickstart-refresh
command whenever your package activations change, such as when you modify the package-load-list value.
We put it inside Auto-tangle hook so when we save this file it runs it automatically.

As I tested, it makes startup about 0.1 seconds faster.
Avg:
- Off: 0.66 sec
- On:  0.59 sec

Package quickstart only works with package.el.
If you plan to use a different package manager, remember to remove this section and the package-quickstart-refresh line in the Auto-tangle hook.
#+begin_src emacs-lisp
(setq package-quickstart t) ;; For blazingly fast startup times, this line makes startup miles faster
#+end_src

*** Package Async
Simple library for asynchronous processing in Emacs.
Makes package installation about 30 sec faster.
Only works with package.el.
#+begin_src emacs-lisp
(use-package async
  :defer
  :custom
  (dired-async-mode t)
  (async-bytecomp-package-mode t)
  (async-bytecomp-allowed-packages '(all))
  (async-package-do-action t))
#+end_src

** Good Defaults
#+begin_src emacs-lisp
(use-package emacs
  :init
  ;; Still needed for terminals
  (setq menu-bar-mode nil)           ;; Disable the menu bar
  ;; (scroll-bar-mode nil)      ;; Disable the scroll bar
  (setq tool-bar-mode nil)           ;; Disable the tool bar

  (setq inhibit-startup-screen t)  ;; Disable welcome screen

  (setq use-file-dialog nil)

  (setq initial-scratch-message nil)
  (setq visible-bell t)
  (setq ring-bell-function 'silent)

  (setq delete-selection-mode t)   ;; Select text and delete it by typing.
  (setq electric-indent-mode nil)  ;; Turn off the weird indenting that Emacs does by default.
  (setq electric-pair-mode t)      ;; Turns on automatic parens pairing

  (setq blink-cursor-mode nil)     ;; Don't blink cursor
  (setq global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed
  (setq use-short-answers t)   ;; Since Emacs 29, `yes-or-no-p' will use `y-or-n-p'

  (setq dired-kill-when-opening-new-dired-buffer t) ;; Dired don't create new buffer
  (setq recentf-mode t) ;; Enable recent file mode

  ;;(global-visual-line-mode t)           ;; Enable line wrapping (NOTE: breaks vundo)
  (setq global-display-line-numbers-mode t)  ;; Display line numbers
  ;;(display-line-numbers-type 'relative) ;; Relative line numbers
  (setq global-hl-line-mode t)               ;; Highlight current line

  (setq native-comp-async-report-warnings-errors 'silent) ;; Don't show native comp errors
  (setq warning-minimum-level :error) ;; Only show errors in warnings buffer

  ;; (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling
  ;; (scroll-conservatively 10) ;; Smooth scrolling
  ;; (scroll-margin 8)

  ;; (pixel-scroll-precision-mode t) ;; Precise pixel scrolling. i.e. smooth scrolling (GUI only)
  ;; (pixel-scroll-precision-use-momentum nil)

  (setq indent-tabs-mode nil) ;; Only use spaces for indentation
  (setq tab-width 4)
  (setq sgml-basic-offset 4) ;; Set Html mode indentation to 4
  (setq c-ts-mode-indent-offset 4) ;; Fix weird indentation in c-ts (C, C++)
  (setq go-ts-mode-indent-offset 4) ;; Fix weird indentation in go-ts

  ;; (display-fill-column-indicator-column 80) ;; Set line length indicator to 80 characters
  (setq whitespace-style '(face tabs tab-mark trailing))

  (setq make-backup-files nil) ;; Stop creating ~ backup files
  (setq auto-save-default nil) ;; Stop creating # auto save files
  (setq delete-by-moving-to-trash t)

  (setq backup-directory-alist `(("." . "~/.saves")))

  :hook
  (prog-mode . hs-minor-mode) ;; Enable folding hide/show globally
  ;; (prog-mode . display-fill-column-indicator-mode) ;; Display line length indicator
  (prog-mode . whitespace-mode)

  :config
  ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
  (setq custom-file (locate-user-emacs-file "custom-vars.el"))
  (load custom-file 'noerror 'nomessage)
  (delete-selection-mode 1)

  :bind (([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
         ;; Zooming In/Out
         ("C-+" . text-scale-increase)
         ("C--" . text-scale-decrease)
         ("<C-wheel-up>" . text-scale-increase)
         ("<C-wheel-down>" . text-scale-decrease))
)
#+end_src

* Custom Recipes

#+begin_src emacs-lisp
(use-package nerd-icons-ivy-rich :vc (:url "https://github.com/seagle0128/nerd-icons-ivy-rich"))
(use-package beacon :vc (:url "https://github.com/Malabarba/beacon"))
(use-package whitespace4r :vc (:url "https://github.com/twlz0ne/whitespace4r.el"))
(use-package project)
(use-package flymake)
#+end_src

* Additional Sources
** Adding the lisp directory to load-path
Adds the lisp directory to Emacs's load path to search for elisp files.
This is necessary because Emacs does not search the entire user-emacs-directory.
The directory name can be anything, just add it to the load-path.
#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "scripts" user-emacs-directory))
#+end_src

** Sourcing the files
To use the elisp files we need to load it.
Notes:
- Don't forget the file and the provide name needs to be the same.
- When naming elisp files, functions, it is recommended to use a group name (e.g. init-, start- or any custom name), so it does not get mixed up with other names, functions.
#+begin_src emacs-lisp
(require 'dired-b2f)
(require 'b2f)
#+end_src

** Using the file
And now we can use everything from that file.
#+begin_src emacs-lisp
    ;; (start/hello)
#+end_src

* Evil Mode

#+begin_src emacs-lisp
(use-package evil
  :init      ;; tweak evil's configuration before loading it
  (setq evil-want-integration nil)
  (setq evil-want-keybinding nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t))
;; (use-package evil-collection
;;   :straight t
;;   :after evil
;;   :config
;;   (setq evil-collection-mode-list '(dashboard dired ibuffer))
;;   (evil-collection-init))
;; (use-package evil-tutor
;;   :straight t)

(use-package whitespace4r
  :defer
  :diminish whitespace4r-mode
  :config
  (whitespace4r-mode 1))
#+end_src

* General Keybindings

#+begin_src emacs-lisp
(use-package general
  :config

  (general-unbind "M-h" "M-j" "M-k" "M-l")
  (general-unbind org-mode-map "M-h")

  (general-define-key
   "M-h" 'left-char
   "M-j" 'evil-next-line
   "M-k" 'evil-previous-line
   "M-l" 'right-char)

  (defconst b2f-leader-key "<f15>")
  ;; set up 'F15' (omg) as the global leader key
  (general-create-definer leader-keys
    :prefix "<f15>") ;; set leader
                                        ;:global-prefix "M-<f24>" ;; access leader in insert mode

  (leader-keys
    "<f15>"   '(counsel-M-x                                                        :wk "Counsel M-x")
    "."       '(find-file                                                          :wk "Find file")
    "f c"     '((lambda () (interactive) (find-file "~/.config/emacs/init.org"))   :wk "Edit emacs config")
    "f r"     '(counsel-recentf                                                    :wk "Find recent files")
    "TAB TAB" '(comment-line                                                       :wk "Comment lines"))

  (leader-keys
    "b"   '(:ignore t          :wk "Buffer...")
    "b b" '(switch-to-buffer   :wk "Switch buffer")
    "b i" '(ibuffer            :wk "Ibuffer")
    "b c" '(kill-this-buffer   :wk "Kill this buffer")
    "b o" '(kill-other-buffers :wk "Kill other buffers")
    "b n" '(next-buffer        :wk "Next buffer")
    "b p" '(previous-buffer    :wk "Previous buffer")
    "b r" '(revert-buffer      :wk "Reload buffer")
    "b s" '(save-buffer        :wk "Save buffer"))

  (leader-keys
    "d"   '(:ignore t :wk "Dired...")
    "d j" '(dired :wk "Dired Jump")
    "d d" '(dired-jump :wk "Open Dired")
    "d 1" '(dired-create-empty-file :wk "Create Empty File")
    "d 2" '(dired-create-directory :wk "Create Directory")
    "d w" '(:ignore t :wk "Writable Dired Mode...")
    "d w w" '(wdired-change-to-wdired-mode :wk "WDired Mode")
    "d w c" '(wdired-finish-edit :wk "Finish Edit")
    "d w ECS" '(wdired-abort-changes :wk "Abort Changes")
  )

  ;; "d n" '(neotree-dir :wk "Open directory in neotree")
  ;; "d p" '(peep-dired :wk "Peep-dired"))

  (leader-keys
    "e"   '(:ignore t           :wk "Evaluate...")
    "e b" '(eval-buffer         :wk "Evaluate elisp in buffer")
    "e d" '(eval-defun          :wk "Evaluate defun containing or after point")
    "e e" '(eval-expression     :wk "Evaluate and elisp expression")
    "e h" '(counsel-esh-history :wk "Eshell history")
    "e l" '(eval-last-sexp      :wk "Evaluate elisp expression before point")
    "e r" '(eval-region         :wk "Evaluate elisp in region")
    "e s" '(eshell              :wk "Eshell"))

  (leader-keys
    "h"     '(:ignore t                                                       :wk "Help...")
    "h f"   '(describe-function                                               :wk "Describe function")
    "h v"   '(describe-variable                                               :wk "Describe variable")
    "h s"   '(describe-symbol                                                 :wk "Describe symbol")
    "h b"   '(describe-bindings                                               :wk "Describe bindings")
    "h k"   '(describe-key                                                    :wk "Describe key")
    "h r r" '((lambda () (interactive) (load-file "~/.config/emacs/init.el")) :wk "Reload emacs config"))
  ;;"h r r" '(reload-init-file :wk "Reload emacs config"))

  (leader-keys
    "m"   '(:ignore t           :wk "Org...")
    "m a" '(org-agenda          :wk "Org agenda")
    "m e" '(org-export-dispatch :wk "Org export dispatch")
    "m i" '(org-toggle-item     :wk "Org toggle item")
    "m t" '(org-todo            :wk "Org todo")
    "m B" '(org-babel-tangle    :wk "Org babel tangle")
    "m T" '(org-todo-list       :wk "Org todo list"))

  (leader-keys
    "m b"   '(:ignore t              :wk "Tables...")
    "m b -" '(org-table-insert-hline :wk "Insert hline in table"))

  (leader-keys
    "m d"   '(:ignore t      :wk "Date/deadline...")
    "m d t" '(org-time-stamp :wk "Org time stamp"))

  (leader-keys
    "l" '(:ignore t :wk "LSP...")
    "l <escape>" '(keyboard-escape-quit :wk t)
    "l r" '(eglot-rename :wk "Rename")
    "l a" '(eglot-code-actions :wk "Code Actions")
    "l f" '(:ignore t :wk "Find...")
    "l f d" '(eglot-find-declaration :wk "Declaration")
    "l f t" '(eglot-find-typeDefinition :wk "Type Definition")
    "l f i" '(eglot-find-implementation :wk "Implementation"))

  (leader-keys
    "p" '(projectile-command-map :wk "Projectile"))

  (leader-keys
    "o"   '(:ignore t      :wk "Open...")
    "o d" '(dashboard-open :wk "Open Dashboard"))

  (leader-keys
    "t"   '(:ignore t                 :wk "Toggle...")
    "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
    "t t" '(visual-line-mode          :wk "Toggle truncated lines"))

  (leader-keys
    "w"   '(:ignore t            :wk "Windows...")
    ;; Window splits
    "w c" '(evil-window-delete   :wk "Close window")
    "w o" '(delete-other-windows :wk "Close other windows")
    "w n" '(evil-window-new      :wk "New window")
    "w s" '(evil-window-split    :wk "Horizontal split window")
    "w v" '(evil-window-vsplit   :wk "Vertical split window")
    ;; Window motions
    "w h" '(evil-window-left     :wk "Window left")
    "w j" '(evil-window-down     :wk "Window down")
    "w k" '(evil-window-up       :wk "Window up")
    "w l" '(evil-window-right    :wk "Window right")
    "w w" '(evil-window-next     :wk "Goto next window"))
  )
#+end_src

* Appearance
Set fonts in the early-init.el file
** Beacon Mode

#+begin_src emacs-lisp
(use-package beacon
  :diminish beacon-mode
  :init
  (beacon-mode 1))
#+end_src

** Nerd Icons
This is an icon set that can be used with dired, ibuffer and other Emacs packages.
Don't forget nerd-icons-install-fonts to install the resource fonts.

We use nerd-icons because it supports both GUI and TUI unlike all-the-icons.
Also Doom modeline requires nerd icons.
#+begin_src emacs-lisp
(use-package nerd-icons :defer)

(use-package nerd-icons-dired
    :diminish nerd-icons-dired-mode
    :after nerd-icons
    :hook (dired-mode . nerd-icons-dired-mode))

(use-package nerd-icons-ibuffer
  :diminish nerd-icons-ibuffer-mode
  :after nerd-icons
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src
** ModeLine

Bottom Bar.

*** Diminish

#+begin_src emacs-lisp
(defun b2f/diminish-all()
  (interactive)
  (diminish 'eldoc)
)

(add-hook 'after-init-hook '#b2f/diminish-all)
#+end_src

*** DoomModeLine (Disabled)

Laggy but beauty.

#+begin_src emacs-lisp :tangle no
(use-package doom-modeline
  :if (display-graphic-p)
  :init
  (setq doom-modeline-height 31)      ;; sets modeline height
  (setq doom-modeline-bar-width 4)    ;; sets right bar width
  ;; (setq doom-modeline-persp-name t)   ;; adds perspective name to modeline
  ;; (setq doom-modeline-persp-con t)   ;; adds folder icon next to persp name
  (setq inhibit-compacting-font-caches t) ;; don’t compact font caches during GC - for performance
  :config
  (doom-modeline-mode 0))

(use-package nyan-mode
  :if (display-graphic-p)
  :init
  (setq nyan-animate-nyancat t)
  :config (nyan-mode 0))
#+end_src

*** MoodModeLine (Disabled)

Less laggy, less beauty.

#+begin_src emacs-lisp :tangle no
(use-package mood-line
  ;; Enable mood-line
  :config
  (mood-line-mode 1)
  :custom
  (setq mood-line-format mood-line-format-default-extended)
  (setq mood-line-glyph-alist mood-line-glyphs-ascii))
#+end_src

** Rainbow Mode

Display the actual color as a background for any hex color value (ex. #BBFFBB).  The code block below enables rainbow-mode in all programming modes (prog-mode) as well as org-mode, which is why rainbow works in this document.

#+begin_src emacs-lisp :tangle no
(use-package rainbow-mode
  :diminish rainbow-mode
  :if (display-graphic-p)
  :hook
  ((org-mode prog-mode) . rainbow-mode))
#+end_src

** Theme

#+begin_src emacs-lisp
;; (use-package doom-themes
;;  :config
;;  (load-theme 'doom-challenger-deep t))

;; (use-package gruvbox-theme
;;   :config
;;   (setq gruvbox-bold-constructs t)
;;   (load-theme 'gruvbox-dark-medium t)) ;; We need to add t to trust this package

;; (use-package solarized-theme
;;   :defer
;;   :if (display-graphic-p)
;;   :init
;;   (load-theme 'solarized-light t))
#+end_src

** Transparency

With Emacs version 29, true transparency has been added.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 90)) ;; For all new frames henceforth

;; Transparency in terminal
(defun start/tui-enable-transparency ()
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))

(add-hook 'window-setup-hook 'start/tui-enable-transparency)
#+end_src

* Development

** Projectile
Project interaction library for Emacs.

Emacs has a built in project manager called project.el, but we don't use it.
You can try it out with the keybinds under C-x p because project.el does not require any special setup to use.

We use projectile because it:
- supports more features and project types.
- has better integration with projects.
- has better documentation.
- is developed faster.
More [[https://docs.projectile.mx/projectile/projectile_vs_project.html][reasons]] to use projectile.

You can also make the [[https://github.com/karthink/consult-dir][consult-dir]] package list all the directories you [[https://github.com/MiniApollo/config/blob/main/emacs/init.org#consult-dir][specified]] and search from them like in tmux-sessionizer.
#+begin_src emacs-lisp
(use-package projectile
  :diminish projectile-mode
  :init
  (projectile-mode +1))
#+end_src

** Eglot
Built in Emacs client for the Language Server Protocol.
We use Eglot because it is fast and minimal.
For more: C-h i: g: (eglot)Top

Eglot does not automatically download LSP servers. It requires separate download.
The easiest way to install LSP servers is with a package manager like mason.el.

If you can't use a package manager you can do the following:
- Download the server (e.g. from github)
- Add the binary/executable to your path.
- Or customize the eglot-server-programs list.
To control how a LSP server is started customize the eglot-server-programs list.

There are many alternative LSP clients, one of them is LSP-mode.
Which has more features and supports automatic language server installation.
But it's bigger, so it has more moving parts.

We don't use it because Eglot is more than enough for most people.
If you want to use LSP mode check out their [[https://emacs-lsp.github.io/lsp-mode/][documentation]] or the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] page for more information.
#+begin_src emacs-lisp
(use-package eglot
  :ensure nil ;; Don't install eglot because it's now built-in
  :hook ((zig-mode
          rust-mode
          go-mode
          typescript-mode
          odin-ts-mode
          odin-mode)
    . eglot-ensure) ;; Autostart lsp servers for a given mode
  :custom
  ;; Good default
  (eglot-events-buffer-size 0) ;; No event buffers (LSP server logs)
  (eglot-autoshutdown t);; Shutdown unused servers.
  (eglot-report-progress nil) ;; Disable LSP server logs (Don't show lsp messages at the bottom, java)
  ;; Manual lsp servers
  :config
  (add-to-list 'eglot-server-programs
               `(odin-mode . ("ols"))) ;; Adds our lua lsp server to eglot's server list
  )
#+end_src

** Mason.el
Package manager for LSP, DAP, linters, and more for the Emacs Operating System.
I waited so long for a package like this.
If you plan to use something like LSP-mode don't forget to remove this.
#+begin_src emacs-lisp
(use-package mason
  :hook (after-init . mason-ensure))
#+end_src

** Sideline-flymake
Show flymake errors with sideline.
#+begin_src emacs-lisp
(use-package sideline-flymake
  :hook (flymake-mode . sideline-mode)
  :custom
  (sideline-flymake-display-mode 'line) ;; Show errors on the current line
  (sideline-backends-right '(sideline-flymake)))
#+end_src

** Yasnippet
A template system for Emacs. And yasnippet-snippets is a snippet collection package.
To use it write out the full keyword (or use autocompletion) and press Tab.
#+begin_src emacs-lisp
(use-package yasnippet
  :hook (prog-mode . yas-minor-mode))

(use-package yasnippet-snippets :defer)

(defun start/corfu-yas-tab-handler ()
  "Prioritize corfu over yasnippet when yasnippet is active"
  (interactive)
  ;; There is no direct way to get if corfu is currently displayed so we watch the completion index
  (if (> corfu--index -1)
      (corfu-complete)
    (yas-next-field-or-maybe-expand)
    ))
(use-package emacs
  :after (yasnippet corfu)
  :bind
  (:map yas-keymap
        ("TAB" . start/corfu-yas-tab-handler)))
#+end_src

** Snippy
VSCode/LSP snippet support for Emacs with Yasnippet.
Uses friendly snippets.
Developed by me.
Note: If you want to use a different package manager you need to change :vc(url ..) part.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
(use-package snippy
  :vc (:url "https://github.com/MiniApollo/snippy.git"
            :branch "main"
            :rev :newest)
  :hook (after-init . global-snippy-minor-mode)
  :custom
  (snippy-global-languages '("global")) ;; Recomended
  ;; Optional
  ;; (snippy-install-dir (expand-file-name <Your location>))
  ;; Use different snippet collections
  ;; (snippy-source '("Your git repo" . "my-snippets-dir"))
  :config
  (snippy-install-or-update-snippets)) ;; Autoupdate git repo
#+end_src

** Tree-Sitter
A parser generator tool and an incremental parsing library.
Check out TJ's [[https://www.youtube.com/watch?v=09-9LltqWLY][video]] to learn why you should use it.

With Emacs 29 Tree-Sitter is now built-in. You may need to compile Emacs from source to have it enabled.
You also need to have a compiler installed so Emacs can compile the parsers into a shared library.
For more info about how to use Tree-Sitter check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][masteringemacs]] article.

Using Tree-Sitter is somewhat hacky because it requires you to:
- manually manage a source list of the parsers you want to use.
- remap the major modes you want to use.
You can also use treesit-auto, but it is updated quite slowly so we don't use it.

To explore the current buffer's syntax tree, use the treesit-explore-mode command.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp
(setq treesit-language-source-alist
      '((bash "https://github.com/tree-sitter/tree-sitter-bash")
        (cmake "https://github.com/uyha/tree-sitter-cmake")
        (c "https://github.com/tree-sitter/tree-sitter-c")
        (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
        (css "https://github.com/tree-sitter/tree-sitter-css")
        (elisp "https://github.com/Wilfred/tree-sitter-elisp")
        (gdscript "https://github.com/PrestonKnopp/tree-sitter-gdscript")
        (go "https://github.com/tree-sitter/tree-sitter-go")
        (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
        (html "https://github.com/tree-sitter/tree-sitter-html")
        (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
        (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
        (json "https://github.com/tree-sitter/tree-sitter-json")
        (make "https://github.com/alemuller/tree-sitter-make")
        (markdown "https://github.com/ikatyang/tree-sitter-markdown")
        (python "https://github.com/tree-sitter/tree-sitter-python")
        (rust "https://github.com/tree-sitter/tree-sitter-rust")
        (toml "https://github.com/tree-sitter/tree-sitter-toml")
        (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
        (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
        (vue "https://github.com/ikatyang/tree-sitter-vue")
        (yaml "https://github.com/ikatyang/tree-sitter-yaml")
        (odin "https://github.com/tree-sitter-grammars/tree-sitter-odin")
        ))

(defun start/install-treesit-grammars ()
  "Install missing treesitter grammars"
  (interactive)
  (dolist (grammar treesit-language-source-alist)
    (let ((lang (car grammar)))
      (unless (treesit-language-available-p lang)
        (treesit-install-language-grammar lang)))))

;; Call this function to install missing grammars
(add-hook 'after-init-hook #'start/install-treesit-grammars)

;; Optionally, add any additional mode remappings not covered by defaults
(setq major-mode-remap-alist
      '((yaml-mode . yaml-ts-mode)
        (sh-mode . bash-ts-mode)
        (c-mode . c-ts-mode)
        (c++-mode . c++-ts-mode)
        (css-mode . css-ts-mode)
        (python-mode . python-ts-mode)
        (mhtml-mode . html-ts-mode)
        (javascript-mode . js-ts-mode)
        (js-json-mode . json-ts-mode)
        (typescript-mode . typescript-ts-mode)
        (conf-toml-mode . toml-ts-mode)
        (gdscript-mode . gdscript-ts-mode)
        (odin-mode . odin-ts-mode)
        ))
(setq treesit-font-lock-level 3)

;; Or if there is no built in mode
(use-package cmake-ts-mode :ensure nil :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))
(use-package go-mod-ts-mode :ensure nil :mode "\\.mod\\'")
(use-package lua-ts-mode :ensure nil :mode "\\.lua\\'")
(use-package rust-ts-mode :ensure nil :mode "\\.rs\\'")
(use-package typescript-ts-mode :ensure nil :mode "\\.ts\\'")
(use-package tsx-ts-mode :ensure nil :mode "\\.tsx\\'")
(use-package yaml-ts-mode :ensure nil :mode ("\\.yaml\\'" "\\.yml\\'"))
#+end_src


* CuaMode

Enables Ctrl+C Ctrl+V Ctrl+Z bindings.

#+begin_src emacs-lisp
(cua-mode 1)
#+end_src

* Buffer Move

#+begin_src emacs-lisp
(use-package buffer-move
  :general
  (leader-keys
    ;; Move Windows
    "w H" '(buf-move-left        :wk "Buffer move left")
    "w J" '(buf-move-down        :wk "Buffer move down")
    "w K" '(buf-move-up          :wk "Buffer move up")
    "w L" '(buf-move-right       :wk "Buffer move right")))
#+end_src

* Completion

** Company Mode

#+begin_src emacs-lisp
(use-package company-mode
  :vc (:url "https://github.com/company-mode/company-mode.git")
  :defer
  :config
  (global-company-mode 1))
#+end_src

** Save History

Persist history over Emacs restarts

#+begin_src emacs-lisp
(use-package savehist
  :defer
  :diminish savehist-mode
  :init
  (savehist-mode 1))
#+end_src

** Ivy + Counsel

#+begin_src emacs-lisp
(use-package ivy
  :diminish ivy-mode
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :config (ivy-mode 1))

(use-package counsel
  :diminish counsel-mode
  ;; :after ivy
  :config (counsel-mode 1))

(use-package ivy-rich
  :diminish ivy-rich-mode
  ;; :after counsel
  :init (setq ivy-rich-path-style 'abbrev
              ivy-virtual-abbreviate 'full)
  :config (ivy-rich-mode 1))

(use-package nerd-icons-ivy-rich
  :diminish nerd-icons-ivy-rich-mode
  :if (display-graphic-p)
  ;; :after ivy-rich
  :config (nerd-icons-ivy-rich-mode 1))
#+end_src

* Vertico (Disabled)

#+begin_src emacs-lisp :tangle no
;; Enable Vertico.
(use-package vertico
  :diminish vertico-mode
  ;; :custom
  ;; (vertico-scroll-margin 0) ;; Different scroll margin
  ;; (vertico-count 20) ;; Show more candidates
  ;; (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
  ;; (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
  :init
  (vertico-mode))

;; Emacs minibuffer configurations.
(use-package emacs
  :custom
  ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
  ;; to switch display modes.
  (context-menu-mode t)
  ;; Support opening new minibuffers from inside existing minibuffers.
  (enable-recursive-minibuffers t)
  ;; Hide commands in M-x which do not work in the current mode.  Vertico
  ;; commands are hidden in normal buffers. This setting is useful beyond
  ;; Vertico.
  (read-extended-command-predicate #'command-completion-default-include-p)
  ;; Do not allow the cursor in the minibuffer prompt
  (minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src

* Dashboard

#+begin_src emacs-lisp
(use-package dashboard
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-startup-banner 'logo)
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-vertically-center-content nil) ;; set to 't' for centered content vertically
  (setq dashboard-items '((recents   . 5)
                        (bookmarks . 5)
                        (projects  . 5)
                        (agenda    . 5)
                        (registers . 5)))
  (setq dashboard-display-icons-p t)     ; display icons on both GUI and terminal
  (setq dashboard-icon-type 'nerd-icons) ; use `nerd-icons' package
  (setq dashboard-projects-backend 'projectile)
  :config
  (dashboard-setup-startup-hook)
)
#+end_src

* Dired

#+begin_src emacs-lisp
(use-package dired
  :ensure nil
  :init
  (setq dired-listing-switches "-avlD --group-directories-first --human-readable")
  (setq dired-omit-files "\\|^\\..+$")
  (setq dired-dwim-target t)
  (setq dired-mouse-drag-files t)
  (setq dired-kill-when-opening-new-dired-buffer t)
)
#+end_src

* Language Support

Emacs has built-in programming language modes for Lisp, Scheme, DSSSL, Ada, ASM, AWK, C, C++, Fortran, Icon, IDL (CORBA), IDLWAVE, Java, Javascript, M4, Makefiles, Metafont, Modula2, Object Pascal, Objective-C, Octave, Pascal, Perl, Pike, PostScript, Prolog, Python, Ruby, Simula, SQL, Tcl, Verilog, and VHDL.  Other languages will require you to install additional modes.

#+begin_src emacs-lisp
(use-package haskell-mode)
(use-package lua-mode)
(use-package typescript-mode)
#+end_src

** Odin

#+begin_src emacs-lisp
(use-package odin-mode
  :vc (:url "https://github.com/mattt-b/odin-mode")
  :mode ("\\.odin\\'" . odin-mode))

(use-package odin-ts-mode
  :vc (:url "https://github.com/Sampie159/odin-ts-mode")
  :mode ("\\.odin\\'" . odin-ts-mode))

(add-to-list 'compilation-error-regexp-alist-alist
             `(odin-compilation-pattern
               ,(rx-to-string
                 '(seq bol
                       (group (any "A-Za-z") ":/" (1+ (not (any "()"))) ".odin")
                       "("
                       (group (1+ digit))
                       ":"
                       (group (1+ digit))
                       ")"
                       (0+ space)
                       (or "Error:" "Syntax Error:" "Warning:" "Info:" "Note:")
                       (0+ not-newline)))
               1 2 3))

(add-to-list 'compilation-error-regexp-alist 'odin-compilation-pattern)
#+end_src

* Multiple Cursors

#+begin_src emacs-lisp
(use-package multiple-cursors
  :config
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
  (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this))
#+end_src

* Org Mode

** Enabling Table of Contents

#+begin_src emacs-lisp
(use-package toc-org
  :commands toc-org-enable
  :hook (org-mode . toc-org-mode))
#+end_src

** Enabling Org Bullets

Org-bullets gives us attractive bullets rather than asterisks.

Disabled because: cause errors.

#+begin_src emacs-lisp
;; (use-package org-superstar
;;   :if (display-graphic-p)
;;   :config
;;   (setq org-superstar-leading-bullet " ")
;;   (setq org-superstar-headline-bullets-list '("◉" "○" "◇" "◈" "◇"))
;;   (setq org-superstar-special-todo-items t) ;; Makes TODO header bullets into boxes
;;   (setq org-superstar-todo-bullet-alist '(("TODO"  . 9744)
;;                                           ("WAIT"  . 9744)
;;                                           ("READ"  . 9744)
;;                                           ("PROG"  . 9744)
;;                                           ("DONE"  . 9745)))
;;   :hook (org-mode . org-superstar-mode))
#+end_src

** Disable Electric Indent

Org mode source blocks have some really weird and annoying default indentation behavior.  I think this has to do with electric-indent-mode, which is turned on by default in Emacs.  So let's turn it OFF!

#+begin_src emacs-lisp
(electric-indent-mode -1)
(setq org-edit-src-content-indentation 0)
#+end_src

** Shift Select

#+begin_src emacs-lisp
(setq org-support-shift-select 'always)
#+end_src

** Org Level Headers

#+begin_src emacs-lisp
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.7))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
 ;; '(org-level-4 ((t (:inherit outline-4 :height 1.4))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.3))))
 '(org-level-6 ((t (:inherit outline-5 :height 1.2))))
 '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
#+end_src

** Source Code Block Tag Expansion

Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                           |
|------------------------+------------------------------------------|
| <a                     | #+begin_export ascii ' … ' #+end_export  |
| <c                     | #+begin_center       ' … ' #+end_center  |
| <C                     | #+begin_comment      ' … ' #+end_comment |
| <e                     | #+begin_example      ' … ' #+end_example |
| <E                     | #+begin_export       ' … ' #+end_export  |
| <h                     | #+begin_export html  ' … ' #+end_export  |
| <l                     | #+begin_export latex ' … ' #+end_export  |
| <q                     | #+begin_quote        ' … ' #+end_quote   |
| <s                     | #+begin_src          ' … ' #+end_src     |
| <v                     | #+begin_verse        ' … ' #+end_verse   |

#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

* Terminal
** Eat
Eat(Emulate A Terminal) is a terminal emulator within Emacs.
It's more portable and less overhead for users over like vterm or eshell.
We setup eat with eshell, if you want to use bash, zsh etc., check out their git [[https://codeberg.org/akib/emacs-eat][repository]] how to do it.

If you want a faster and more responsive terminal emulator try out vterm.
#+begin_src emacs-lisp
(use-package eat
  :vc (:url "https://codeberg.org/akib/emacs-eat.git")
  :defer
  :hook ('eshell-load-hook #'eat-eshell-mode))
#+end_src

** Exec-path-from-shell
Make Emacs use the $PATH set up by the user's shell
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :hook (after-init . exec-path-from-shell-initialize))
#+end_src

* Scroll Behavior

Smooth animated scroll behavior.

#+begin_src emacs-lisp
(use-package good-scroll
  :diminish good-scroll-mode
  :init
  (setq good-scroll-render-rate 0.01)
  :config
  (good-scroll-mode 1))

(global-set-key [next] #'good-scroll-up-full-screen)
(global-set-key [prior] #'good-scroll-down-full-screen)
#+end_src

* Which Key

#+begin_src emacs-lisp
  (use-package which-key
    :diminish which-key-mode
    :init
    (which-key-mode 1)
    :config
    (setq which-key-side-window-location 'bottom
          which-key-sort-order #'which-key-key-order-alpha
          which-key-sort-uppercase-first nil
          which-key-add-column-padding 1
          which-key-max-display-columns nil
          which-key-min-display-lines 6
          which-key-side-window-slot -10
          which-key-side-window-max-height 0.25
          which-key-idle-delay 0.8
          which-key-max-description-length 25
          which-key-allow-imprecise-window-fit nil
          which-key-separator " -> " ))
#+end_src

* Uncategorized

#+begin_src emacs-lisp

;;; Start maximised (cross-platf)
(add-hook 'window-setup-hook 'toggle-frame-maximized t)
(add-hook 'server-after-make-frame-hook 'toggle-frame-maximized t)

(set-charset-priority 'unicode)
(setq locale-coding-system 'utf-8
      coding-system-for-read 'utf-8
      coding-system-for-write 'utf-8)
(set-clipboard-coding-system 'utf-16le)
(set-selection-coding-system 'utf-16le)          ; correct
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))

;;; Move-Text
(use-package move-text
  :init
  (move-text-default-bindings))

;;; Modes

(use-package markdown-mode
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown")
  :bind (:map markdown-mode-map
              ("C-c C-e" . markdown-do)))

(use-package rg
  :general
  (leader-keys
    "r" '(rg-menu :which-key "RipGrep...")))
#+end_src
